# Generated by Django 4.2.6 on 2023-12-22 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0002_alter_comment_created_at_alter_topic_created_by'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='liked_topics',
            field=models.ManyToManyField(blank=True, to='topics.topic'),
        ),
    ]
